spring:
  datasource:
    url: jdbc:h2:file:./mydb;AUTO_SERVER=TRUE
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      data-locations: data.sql
      mode: always
