INSERT INTO DOCTOR (FISCAL_CODE, NAME, SURNAME)
    VALUES ('BOVRNK86R6HA433X', 'Luigi', 'Rozzani');
INSERT INTO DOCTOR (FISCAL_CODE, NAME, SURNAME)
    VALUES ('BOVRNK89R6PP433Y', 'Samuele', 'Soratti');
INSERT INTO DOCTOR (FISCAL_CODE, NAME, SURNAME)
    VALUES ('BOVEEE99R69PP999Y', 'Valeria', 'Giovetti');

INSERT INTO PATIENT (FISCAL_CODE, NAME, SURNAME, DOCTOR_FISCAL_CODE, ADDITIONAL_INFO)
    VALUES ('KVCLND01B24Z129T', 'Giorgia', 'Franchetti', 'BOVRNK89R6PP433Y', 'sottopeso');
INSERT INTO PRESSURE_MEASUREMENT(DATE_TIME, DIASTOLIC_PRESSURE, SISTOLIC_PRESSURE, SYMPTOMS_BIT_STRING, PATIENT_FISCAL_CODE)
    VALUES ( NOW(), 180, 90, 14, 'KVCLND01B24Z129T' );
INSERT INTO PATIENT (FISCAL_CODE, NAME, SURNAME, DOCTOR_FISCAL_CODE, ADDITIONAL_INFO)
    VALUES ('KVCLND01B24Z339T', 'Riccardo', 'Albelli', 'BOVRNK89R6PP433Y', '');
INSERT INTO PRESSURE_MEASUREMENT(DATE_TIME, DIASTOLIC_PRESSURE, SISTOLIC_PRESSURE, SYMPTOMS_BIT_STRING, PATIENT_FISCAL_CODE)
    VALUES ( NOW(), 180, 90, 0, 'KVCLND01B24Z339T' );

-- dottore
INSERT INTO DOCTOR (FISCAL_CODE, NAME, SURNAME, EMAIL)
    VALUES ('BNCRNI85R63A433X', 'Mario', 'Bruno', 'mario.bruno@italia.it');
-- paziente collegato al dottor Bruno
INSERT INTO PATIENT (FISCAL_CODE, NAME, SURNAME, DOCTOR_FISCAL_CODE, ADDITIONAL_INFO)
    VALUES ('VRDLSE99A41F205P', 'Matteo', 'Bellini', 'BNCRNI85R63A433X', 'fumatore, leggermente sovrappeso');
-- terapia per il paziente Matteo
INSERT INTO THERAPY(ID, DOCTOR_FISCAL_CODE, PATIENT_FISCAL_CODE)
    VALUES (1, 'BNCRNI85R63A433X', 'VRDLSE99A41F205P');
-- farmaci legati alla terapia di matteo
INSERT INTO PRESCRIPTION(ID, INDICATIONS, NAME, SUGGESTED_QUANTITY, TIMES_PER_DAY, THERAPY_ID)
    VALUES (1, 'dopo i pasti', 'Farmaco A', 10, 2, 1);
INSERT INTO PRESCRIPTION(ID, INDICATIONS, NAME, SUGGESTED_QUANTITY, TIMES_PER_DAY, THERAPY_ID)
    VALUES (2, 'a colazione', 'Farmaco B', 2, 1, 1);
INSERT INTO PRESCRIPTION(ID, INDICATIONS, NAME, SUGGESTED_QUANTITY, TIMES_PER_DAY, THERAPY_ID)
    VALUES (3, '', 'Farmaco C', 100, 1, 1);
-- misurazione della pressione
INSERT INTO PRESSURE_MEASUREMENT(DATE_TIME, DIASTOLIC_PRESSURE, SISTOLIC_PRESSURE, SYMPTOMS_BIT_STRING, PATIENT_FISCAL_CODE)
    VALUES ( NOW(), 180, 90, 6, 'VRDLSE99A41F205P' );

UPDATE PATIENT SET THERAPY_ID = 1 WHERE FISCAL_CODE = 'VRDLSE99A41F205P';
