INSERT INTO DOCTOR (FISCAL_CODE, NAME, SURNAME)
    VALUES ('BNCRNI85R63A433X', 'Mario', 'Bruno');
INSERT INTO DOCTOR (FISCAL_CODE, NAME, SURNAME)
    VALUES ('BOVRNK86R6HA433X', 'Luigi', 'Rozzani');
INSERT INTO DOCTOR (FISCAL_CODE, NAME, SURNAME)
    VALUES ('BOVRNK89R6PP433Y', 'Samuele', 'Soratti');
INSERT INTO DOCTOR (FISCAL_CODE, NAME, SURNAME)
    VALUES ('BOVEEE99R69PP999Y', 'Valeria', 'Giovetti');
INSERT INTO PATIENT (FISCAL_CODE, NAME, SURNAME)
    VALUES ('VRDLSE99A41F205P', 'Matteo', 'Bellini');
INSERT INTO PATIENT (FISCAL_CODE, NAME, SURNAME)
    VALUES ('KVCLND01B24Z129T', 'Giorgia', 'Franchetti');
INSERT INTO PATIENT (FISCAL_CODE, NAME, SURNAME)
    VALUES ('KVCLND01B24Z339T', 'Riccardo', 'Albelli');
